# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

stages:
- stage: Playground Stage
  jobs:
  - job: Playground
    steps:
    - task: PowerShell@2
      displayName: 'Run a one-line script'
      inputs:
        targetType: inline
        script: Write-Host "Hello, world!"

    - task: PowerShell@2
      displayName: 'Run a multi-line script'
      inputs:
        targetType: inline
        script:|
          Write-Host 'Add other tasks to build, test, and deploy your project.'
          Write-Host 'See https://aka.ms/yaml'