
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# $var = Get-ChildItem -Path "$(Build.SourcesDirectory)\OnlineHelp" -Directory | Select-Object Name | foreach {$_.Name}

trigger:
- master

variables:
  name: content

pool:
  vmImage: windows-latest

stages:
- stage: Playground_Stage
  jobs:
  - job: Playground_Job
    steps:
    - template: azure-template.yml
      parameters:
        text: "Thomas"