
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

stages:
- stage: Playground_Stage
  jobs:
  - job: Playground_Job
    steps:
    - task: PowerShell@2
      displayName: 'Run a one-line script'
      name: Step1
      inputs:
        targetType: inline
        script: 
          Write-Host "Hello, world!"
          $var = Get-ChildItem -Path "$(Build.SourcesDirectory)\OnlineHelp" -Directory | Select-Object Name | foreach {$_.Name}
          Write-Host "##vso[task.setvariable variable=test](Get-Variable var)'

    - task: PowerShell@2
      displayName: 'Run a multi-line script'
      name: Step2
      inputs:
        targetType: inline
        script:
          Write-Host $(test)