
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# $var = Get-ChildItem -Path "$(Build.SourcesDirectory)\OnlineHelp" -Directory | Select-Object Name | foreach {$_.Name}

trigger:
- none

variables:
  name: content

pool:
  vmImage: windows-latest

stages:
- stage: Playground_Stage
  jobs:
  - job: Playground_Job
    steps:
    - checkout: self
    - task: CmdLine@2
      inputs:
        script:
          echo "Structure of work folder of this pipeline:"
          tree $(Agent.WorkFolder)\1 /f
    - task: CopyFiles@2
      displayName: Copying health folder
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)\thomatte.Playground\health'
        contents: '**'
        targetFolder: '$(Build.StagingDirectory)\health'  

    - task: ArchiveFiles@2
      displayName: Archive Build as ZIP
      inputs:
        rootFolderOrFile: '$(Build.StagingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)\Build.zip'
        replaceExistingArchive: true        
      
    - task: PublishPipelineArtifact@1
      displayName: Publish Build Artifact
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)\Build.zip'
        ArtifactName: 'Build'
